"""
Dashboard API Endpoints
Provides adaptive insights and user performance data for dashboard display
"""

import logging
from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy import text
from typing import Optional
import json

from database import SessionLocal
from auth_service import get_current_user
from utils.timezone_utils import now_ist

def get_db_session():
    """Get database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/adaptive-insights")
async def get_adaptive_insights(
    current_user: dict = Depends(get_current_user),
    db=Depends(get_db_session)
):
    """
    Get adaptive insights for dashboard display
    Returns all-time and recent insights generated by UPDATE_INSIGHTS job
    """
    try:
        user_id = current_user['id']
        logger.info(f"Fetching adaptive insights for user {user_id}")
        
        # Fetch dashboard insights
        dashboard_result = db.execute(text("""
            SELECT all_time_insights, recent_insights, last_updated_at
            FROM user_dashboard_insights
            WHERE user_id = :user_id
        """), {"user_id": user_id})
        
        dashboard_row = dashboard_result.fetchone()
        
        # Fetch pre-session insights
        presession_result = db.execute(text("""
            SELECT insight_card, last_updated_at
            FROM user_pre_session_insights
            WHERE user_id = :user_id
        """), {"user_id": user_id})
        
        presession_row = presession_result.fetchone()
        
        if not dashboard_row:
            logger.warning(f"No dashboard insights found for user {user_id}")
            return {
                "status": "no_data",
                "message": "Complete a session to generate insights",
                "all_time_markdown": "Start your learning journey! Complete your first session to see insights.",
                "recent_markdown": "No recent sessions yet.",
                "last_updated_at": now_ist().isoformat()
            }
        
        # Parse the insights
        all_time_insights = dashboard_row[0]
        recent_insights = dashboard_row[1]
        last_updated = dashboard_row[2]
        
        # Extract markdown from the JSONB structure
        all_time_markdown = ""
        recent_markdown = ""
        
        if isinstance(all_time_insights, dict):
            all_time_markdown = all_time_insights.get('markdown', '')
        
        if isinstance(recent_insights, dict):
            recent_markdown = recent_insights.get('markdown', '')
        
        # Prepare response
        response = {
            "status": "success",
            "all_time_markdown": all_time_markdown,
            "recent_markdown": recent_markdown,
            "last_updated_at": last_updated.isoformat() if last_updated else now_ist().isoformat(),
        }
        
        # Add pre-session insights if available
        if presession_row:
            insight_card = presession_row[0]
            if isinstance(insight_card, dict):
                response["pre_session_card"] = insight_card
        
        logger.info(f"Successfully fetched adaptive insights for user {user_id}")
        return response
        
    except Exception as e:
        logger.error(f"Error fetching adaptive insights: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to fetch adaptive insights: {str(e)}")
    finally:
        db.close()
