# SINGLE SOURCE OF TRUTH - CANONICAL TAXONOMY FROM ENRICHED CSV
CANONICAL_TAXONOMY = {
    "Arithmetic": {
        "Time-Speed-Distance": {
            "description": "Time-Speed-Distance problems involve the relationship between how fast an object moves (speed), how long it takes to move (time), and how far it travels (distance). The fundamental formula connecting these quantities is distance = speed \u00d7 time. Speed is typically measured in units like meters per second (m/s), kilometers per hour (km/h), or miles per hour (mph). Time can be in seconds, minutes, hours, etc., and distance in meters, kilometers, miles, etc. It's crucial to ensure consistent units throughout the calculation. Common problem variants include calculating the time taken given speed and distance, finding the speed given time and distance, or determining the distance traveled given speed and time. Relative speed problems, involving two or more objects moving simultaneously, are also common and may involve objects moving in the same or opposite directions. A frequent trap is using inconsistent units, so always convert units to be compatible before applying the formula.",
            "types": {
                "Basics": "Basic Time-Speed-Distance questions focus on the direct application of the core formula: distance = speed \u00d7 time. These questions typically provide two of the three quantities (speed, time, distance) and ask for the third. For example, you might be given the speed of a car and the time it travels and asked to calculate the distance covered. Alternatively, you could be given the distance and time and asked to find the speed. The key is to correctly identify the givens and the unknown, then rearrange the formula accordingly. Variations might involve converting units before applying the formula, such as converting minutes to hours or kilometers to meters. These questions lay the foundation for more complex Time-Speed-Distance problems.",
                "Relative Speed": "Relative speed problems focus on the effective speed of one object with respect to another, particularly when they are moving towards or away from each other. The intent is typically to determine when they will meet, overtake, or reach a certain separation. Givens often include the individual speeds of the objects and their initial distance apart. Key transformations involve adding the speeds when objects move in opposite directions and subtracting them when they move in the same direction. Frequent variations include objects starting at different times, objects moving in a circular path, and scenarios involving streams or currents affecting the speed of a boat or swimmer.",
                "Circular Track Motion": "Circular Track Motion problems involve objects moving along a circular path. The intent is typically to determine when objects meet or overtake each other, or how many laps are completed in a given time. Givens often include the length of the track, the speeds of the objects, and their starting positions. Standard transformations involve relating the distance traveled to the circumference of the track. Frequent variations include objects moving in the same or opposite directions, and objects starting at the same point or different points on the track. Calculations often involve concepts like relative speed and the least common multiple (LCM) of times or distances.",
                "Boats and Streams": "Boats and Streams problems are a specific type of Time-Speed-Distance problem that involve the motion of a boat in a river or stream. The intent is to calculate the boat's speed in still water, the speed of the stream (current), or the time taken to travel a certain distance upstream or downstream. Givens typically include the boat's speed in still water or its speed relative to the stream (upstream or downstream speed), and the speed of the stream. Unknowns might be the boat's speed in still water, the speed of the stream, or the time taken for a specific journey. Standard transformations involve adding the boat's speed and the stream's speed for downstream travel, and subtracting the stream's speed from the boat's speed for upstream travel. Frequent variations include cases where the boat travels a certain distance upstream and then returns downstream, or where the boat travels across the stream (perpendicular to the current).",
                "Trains": "Train problems are a specific type of Time-Speed-Distance problem that often involve two or more trains. These problems typically ask about the time it takes for trains to meet, pass each other, or cover a certain distance. Givens often include the speeds and lengths of the trains, and the distance between them or the time elapsed. Unknowns might be the time to meet, the speed of one train, or the length of a train. A common transformation is to consider the relative speed of the trains when they are moving in the same or opposite directions. Variations include trains passing through tunnels or crossing bridges, where the length of the train and the length of the tunnel/bridge become important factors. Carefully consider the frame of reference (relative speed) and the effective distance traveled (including train lengths) when solving these problems.",
                "Races": "Race problems, a specific type of Time-Speed-Distance problem, focus on the relative motion of two or more entities competing to cover a certain distance. The intent is typically to determine who wins, by how much, or when a particular racer overtakes another. Givens might include the speeds of the racers, the starting time, the length of the track, or the time taken by one racer to finish. Unknowns could be the finishing time of another racer, the distance covered when one racer overtakes another, or the speed required to win. Standard transformations include calculating the relative speed of two racers and using it to determine the time or distance at which they meet. Frequent variations include races with head starts, races with varying speeds, and circular tracks."
            }
        },
        "Time-Work": {
            "description": "Time-Work problems explore the relationship between the time taken to complete a task and the efficiency or rate of work of individuals or groups. These problems involve quantities like the amount of work, the time taken, and the rate of work, often expressed as work done per unit of time. A fundamental principle is that the amount of work done is directly proportional to the time taken and the rate of work (Work = Time * Rate). Common variants include problems involving multiple workers working together or separately, problems where the rate of work varies, and problems involving pipes filling or emptying tanks. A typical trap is to assume that times add linearly when workers collaborate; instead, rates add. To map story problems to math, identify the work to be done, the time taken by each worker individually, and then determine the combined rate or the combined time based on the scenario.",
            "types": {
                "Work Time Effeciency": "Work-Time Efficiency problems focus on the efficiency or rate at which work is performed. These problems typically involve determining the rate of work of individuals or groups, comparing efficiencies, or finding the time taken to complete a task given the rates of work. The givens might include the amount of work, the time taken by different workers, or their individual rates. Unknowns typically involve finding the rate of a worker, the time required to complete a task, or comparing efficiencies. Standard transformations involve using the relationship Work = Time * Rate and manipulating it to solve for the desired quantity. Frequent variations include cases where the total work is not explicitly given but can be assumed to be a unit, and cases where the efficiency of workers is compared as a ratio or percentage.",
                "Pipes and Cisterns": "Pipes and cisterns problems are a specific type of time-work problem where pipes fill (inlet) or empty (outlet) a cistern (tank). The intent is to determine the time taken to fill or empty the cistern, given the flow rates of the pipes. Givens typically include the individual fill or empty times for each pipe. Standard transformations involve converting these times to rates, where an inlet pipe has a positive rate and an outlet pipe has a negative rate. Frequent variations include multiple pipes working simultaneously, pipes being opened or closed at different times, and finding the net effect of combined inlet and outlet pipes. The underlying principle remains that the net rate of fill/empty is the algebraic sum of the individual rates.",
                "Work Equivalence": "Work Equivalence problems focus on scenarios where different individuals or groups perform equivalent amounts of work, though potentially at different rates and over different durations. The givens typically include information about the work rates or times for individual workers or groups. The intent is to find the unknown time or rate for a specific worker or group to complete an equivalent amount of work. Standard transformations involve equating the work done by different entities, often by expressing the work as the product of rate and time. Frequent variations include cases where the total work is not explicitly stated but implied by the equivalence of work done by different parties. Problems may also involve fractional work completion, requiring careful consideration of the proportion of work done by each entity."
            }
        },
        "Ratios and Proportions": {
            "description": "Ratios and proportions involve comparing quantities. A ratio expresses the relative size of two or more values. It can be represented as a fraction, colon, or using the word \"to\". Proportions are statements that two ratios are equivalent. Solving proportion problems often involves cross-multiplication or finding a common multiplier. A key relationship is that the product of the means equals the product of the extremes. Common variants involve comparing part-to-part ratios versus part-to-whole ratios. A typical trap is to confuse the ratio order or misinterpret the given quantities. To map story problems to math, identify the quantities being compared and express them as a ratio or proportion based on the problem's wording.",
            "types": {
                "Simple Rations": "Simple ratio problems focus on comparing two quantities directly. They typically involve expressing the relationship between two given quantities in simplest form. The givens are the two quantities being compared. The unknown is the simplified ratio, often expressed as a fraction or with a colon. Standard transformations include simplifying fractions by dividing by the greatest common divisor. Frequent variations involve different units of measurement, requiring conversion before simplification. The intent is to quantify the relative magnitude of one quantity compared to another.",
                "Compound Ratios": "Compound ratios involve combining multiple ratios. The intent is to find the overall ratio resulting from the product of individual ratios. Givens typically include multiple ratios, each expressing a relationship between different quantities or the same quantity at different points in time. Unknowns might be the combined ratio or the value of one of the quantities involved. Standard transformations involve multiplying the corresponding terms of the individual ratios to get the compound ratio. For instance, if a:b and c:d are two ratios, the compound ratio is ac:bd. Frequent variations include problems involving changes in multiple quantities or successive changes in the same quantity.",
                "Direct and Inverse Variation": "Direct and inverse variations describe specific relationships between two variables in a proportion. Direct variation means that as one variable increases, the other increases proportionally, or as one decreases, the other decreases proportionally. The relationship is expressed as y = kx, where k is the constant of variation. Givens might include pairs of values for x and y, or information about how one variable changes in relation to the other. Standard transformations involve solving for k and then using it to find other values of x or y. Inverse variation means that as one variable increases, the other decreases proportionally, and vice versa. This is represented by y = k/x. Frequent variations involve finding the constant of variation and using it to predict values, or determining whether a relationship is direct or inverse based on given data.",
                "Partnerships": "Partnership problems involve the distribution of profits or losses among partners in a business venture. The intent is to determine each partner's share based on their contribution (capital, time, or effort). Givens typically include the individual contributions of each partner and the total profit or loss. Unknowns are the individual shares of the profit or loss. Standard transformations involve setting up proportions based on the contributions and solving for the unknowns. Frequent variations include different contribution types (e.g., capital and time) and unequal profit/loss sharing agreements. It's crucial to accurately represent each partner's contribution in the proportion to determine their fair share."
            }
        },
        "Percentages": {
            "description": "Percentages represent proportions or fractions of a whole expressed as parts out of 100. They involve a base quantity, a percentage rate, and a resulting percentage amount. The fundamental relationship is percentage amount = base * (percentage rate / 100). Common variants include calculating the percentage rate given the base and percentage amount, or finding the base given the percentage rate and percentage amount. Percentage problems often involve increases or decreases, requiring careful attention to whether the change is relative to the original or the new value. Story problems involving percentages can be mapped to mathematical expressions by identifying the base, the percentage rate, and whether an increase or decrease is involved. Traps to avoid include confusing the percentage amount with the percentage rate and incorrectly applying percentage changes sequentially.",
            "types": {
                "Basics": "Basic percentage problems focus on the direct application of the core percentage formula: percentage amount = base * (percentage rate / 100). Typically, two of these three quantities are given, and the goal is to find the third. The givens might be presented directly or embedded within a story problem. Standard transformations include converting the percentage rate to a decimal by dividing by 100 and rearranging the formula to solve for the unknown quantity. Frequent variations involve expressing the percentage rate as a fraction or converting between different units for the base and percentage amount. The intent is to solidify understanding of the fundamental relationship between base, percentage rate, and percentage amount.",
                "Percentage Change": "Percentage change questions focus on the difference between an initial value and a final value, expressed as a percentage of the initial value. They typically involve finding the percentage increase or decrease, given the initial and final values. The formula for percentage change is [(final value - initial value) / initial value] * 100. Common variations include finding the final value given the initial value and the percentage change, or finding the initial value given the final value and the percentage change. Transformations often involve converting the percentage change to a decimal and then applying it to the initial value. Frequent variations include percentage increase (positive change) and percentage decrease (negative change). It's crucial to correctly identify the initial value as the base for the percentage change calculation.",
                "Successive Percentage Change": "Successive percentage changes involve applying multiple percentage increases or decreases to a base value. The intent is to find the final value after a series of percentage changes. The givens are typically the initial value and the sequence of percentage changes. The key is to avoid simply adding or subtracting the percentages. Instead, each percentage change must be applied to the result of the previous change. The base value changes after each percentage change. For instance, if a value increases by 10% and then decreases by 10%, the final value is not the same as the original value. Frequent variations include finding the overall percentage change after a series of changes or determining an unknown percentage change given the initial and final values. The standard transformation involves multiplying the base value by (1 + percentage change) for each successive change."
            }
        },
        "Averages and Alligation": {
            "description": "Averages and Alligation deal with central tendency and mixture problems. The average (arithmetic mean) is the sum of all values divided by the number of values. Quantities involved are typically numerical values representing things like scores, prices, speeds, or weights. Key formulas include the basic average formula and weighted average formula. Common variants include finding the missing value given the average, calculating the average speed for a journey with different speeds, and weighted averages of different quantities. Traps include failing to account for weights in weighted averages and incorrectly handling units. Story problems can be mapped by identifying the total sum, the number of items, and any weights associated with the items.",
            "types": {
                "Basic Averages": "Basic average questions involve finding the arithmetic mean of a set of numbers. The givens are usually a set of numerical values, and the unknown is their average. Standard transformations include summing the given values and dividing by the number of values. Frequent variations include finding the sum given the average and the number of values, finding the number of values given the sum and the average, and finding a missing value given the average and the remaining values. The intent is to assess understanding of the core concept of the arithmetic mean.",
                "Weighted Averages": "Weighted average questions focus on finding the average of values when each value has a different weight or frequency. The givens usually include individual values and their corresponding weights or frequencies. The unknown is typically the weighted average or a missing value/weight. Standard transformations involve multiplying each value by its weight, summing these products, and dividing by the total weight. Frequent variations involve combining groups with different weighted averages or finding the weight needed to achieve a target weighted average. The intent is to find a representative average that accounts for the varying importance or frequency of the values."
            }
        }
    }
}
